# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: lfm Documentation
site_url: https://lfm.twango.dev

repo_url: https://github.com/twangodev/lfm-api
repo_name: twangodev/lfm-api
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    annotation: material/arrow-right-circle
  palette:
    - primary: red
    - accent: red
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to system preference


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - search.suggest
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - lfm-api:
      - lfm-api/index.md
  - lfm-cli:
      - lfm-cli/index.md