# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

INHERIT: base.yml

plugins:
  - search
  - offline
  - social
  - git-committers:
      repository: twangodev/lfm-api
      branch: main
      token: !ENV ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      length: -1
  - open-in-new-tab

extra:
  analytics:
    provider: google
    property: G-G26PS920FC

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
