name: Publish Go Module on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: List and publish Go module
        run: |
          module_name=$(go list -m)
          module_version=$(git describe --tags)
          GOPROXY=proxy.golang.org go list -m $module_name@$module_version

      - name: Verify module publication
        run: |
          module_name=$(go list -m)
          module_version=$(git describe --tags)
          attempts=0
          success=0
          while [ $attempts -lt 10 ]; do
            if GOPROXY=proxy.golang.org go list -m $module_name@$module_version; then
              echo "Module $module_name@$module_version has been published successfully."
              success=1
              break
            else
              echo "Verification attempt $((attempts + 1)) failed. Retrying in 30 seconds..."
              sleep 30
            fi
            attempts=$((attempts + 1))
          done
          if [ $success -eq 0 ]; then
            echo "Failed to verify module publication after 10 attempts."
            exit 1
          fi
